/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author clare
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }
    
    String userName;

    HomePage(String u) {
        initComponents();
        this.userName = u;
        //userNameAppear.setText("Hello, " + userName + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        overviewPanel = new javax.swing.JPanel();
        noTickets = new javax.swing.JLabel();
        ttlTickets = new javax.swing.JLabel();
        noRoutes = new javax.swing.JLabel();
        ttlRoutes = new javax.swing.JLabel();
        noBuses = new javax.swing.JLabel();
        ttlBuses = new javax.swing.JLabel();
        ovrvwTxt = new javax.swing.JLabel();
        ticketPanel = new javax.swing.JPanel();
        ttlTxt1 = new javax.swing.JLabel();
        noTickets1 = new javax.swing.JLabel();
        addTicketsBtn = new javax.swing.JButton();
        viewTicketsBtn = new javax.swing.JButton();
        busPanel = new javax.swing.JPanel();
        ttlTxt2 = new javax.swing.JLabel();
        noTickets2 = new javax.swing.JLabel();
        addBusBtn = new javax.swing.JButton();
        busPanel1 = new javax.swing.JPanel();
        ttlTxt3 = new javax.swing.JLabel();
        noTickets3 = new javax.swing.JLabel();
        addDriversBtn = new javax.swing.JButton();
        busPanel2 = new javax.swing.JPanel();
        ttlTxt4 = new javax.swing.JLabel();
        noTickets4 = new javax.swing.JLabel();
        addRoutesBtn = new javax.swing.JButton();
        noTickets5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        rootPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setPreferredSize(new java.awt.Dimension(227, 720));

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        overviewPanel.setBackground(new java.awt.Color(255, 255, 255));
        overviewPanel.setPreferredSize(new java.awt.Dimension(784, 112));

        noTickets.setFont(new java.awt.Font("Open Sans", 1, 23)); // NOI18N
        noTickets.setForeground(new java.awt.Color(255, 159, 28));
        noTickets.setText("000");

        ttlTickets.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        ttlTickets.setForeground(new java.awt.Color(85, 85, 85));
        ttlTickets.setText("Total Ticketss");

        noRoutes.setFont(new java.awt.Font("Open Sans", 1, 23)); // NOI18N
        noRoutes.setForeground(new java.awt.Color(255, 159, 28));
        noRoutes.setText("000");

        ttlRoutes.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        ttlRoutes.setForeground(new java.awt.Color(85, 85, 85));
        ttlRoutes.setText("Total Routes");

        noBuses.setFont(new java.awt.Font("Open Sans", 1, 23)); // NOI18N
        noBuses.setForeground(new java.awt.Color(255, 159, 28));
        noBuses.setText("000");

        ttlBuses.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        ttlBuses.setForeground(new java.awt.Color(85, 85, 85));
        ttlBuses.setText("Total Buses");

        javax.swing.GroupLayout overviewPanelLayout = new javax.swing.GroupLayout(overviewPanel);
        overviewPanel.setLayout(overviewPanelLayout);
        overviewPanelLayout.setHorizontalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ttlTickets)
                    .addComponent(noTickets))
                .addGap(230, 230, 230)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ttlRoutes)
                    .addComponent(noRoutes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ttlBuses)
                    .addComponent(noBuses))
                .addGap(74, 74, 74))
        );
        overviewPanelLayout.setVerticalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overviewPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addComponent(ttlBuses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noBuses))
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addComponent(ttlRoutes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noRoutes))
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addComponent(ttlTickets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noTickets)))
                .addGap(23, 23, 23))
        );

        ovrvwTxt.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        ovrvwTxt.setForeground(new java.awt.Color(255, 159, 28));
        ovrvwTxt.setText("Overview");

        ticketPanel.setBackground(new java.awt.Color(28, 162, 150));
        ticketPanel.setPreferredSize(new java.awt.Dimension(246, 147));

        ttlTxt1.setFont(new java.awt.Font("Open Sans", 1, 22)); // NOI18N
        ttlTxt1.setForeground(new java.awt.Color(255, 255, 255));
        ttlTxt1.setText("Tickets");

        noTickets1.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        noTickets1.setForeground(new java.awt.Color(255, 255, 255));
        noTickets1.setText("Manange bookings, and  add tickets.");

        addTicketsBtn.setBackground(new java.awt.Color(255, 159, 28));
        addTicketsBtn.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        addTicketsBtn.setForeground(new java.awt.Color(255, 255, 255));
        addTicketsBtn.setText("Add Now");
        addTicketsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 159, 28), 1, true));
        addTicketsBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        addTicketsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTicketsBtnActionPerformed(evt);
            }
        });

        viewTicketsBtn.setBackground(new java.awt.Color(28, 162, 150));
        viewTicketsBtn.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        viewTicketsBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewTicketsBtn.setText("View All");
        viewTicketsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        viewTicketsBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        viewTicketsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTicketsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ticketPanelLayout = new javax.swing.GroupLayout(ticketPanel);
        ticketPanel.setLayout(ticketPanelLayout);
        ticketPanelLayout.setHorizontalGroup(
            ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketPanelLayout.createSequentialGroup()
                        .addComponent(addTicketsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewTicketsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(noTickets1)
                    .addComponent(ttlTxt1))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        ticketPanelLayout.setVerticalGroup(
            ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ttlTxt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTickets1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTicketsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewTicketsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        busPanel.setBackground(new java.awt.Color(255, 255, 255));
        busPanel.setPreferredSize(new java.awt.Dimension(246, 147));

        ttlTxt2.setFont(new java.awt.Font("Open Sans", 1, 22)); // NOI18N
        ttlTxt2.setForeground(new java.awt.Color(255, 159, 28));
        ttlTxt2.setText("Bus");

        noTickets2.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        noTickets2.setForeground(new java.awt.Color(51, 51, 51));
        noTickets2.setText("Add buses and assign drivers");

        addBusBtn.setBackground(new java.awt.Color(28, 162, 150));
        addBusBtn.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        addBusBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBusBtn.setText("Add Now");
        addBusBtn.setBorder(null);
        addBusBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        addBusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busPanelLayout = new javax.swing.GroupLayout(busPanel);
        busPanel.setLayout(busPanelLayout);
        busPanelLayout.setHorizontalGroup(
            busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTickets2)
                    .addComponent(ttlTxt2))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        busPanelLayout.setVerticalGroup(
            busPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ttlTxt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTickets2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(addBusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        busPanel1.setBackground(new java.awt.Color(255, 255, 255));
        busPanel1.setPreferredSize(new java.awt.Dimension(246, 147));

        ttlTxt3.setFont(new java.awt.Font("Open Sans", 1, 22)); // NOI18N
        ttlTxt3.setForeground(new java.awt.Color(255, 159, 28));
        ttlTxt3.setText("Drivers");

        noTickets3.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        noTickets3.setForeground(new java.awt.Color(51, 51, 51));
        noTickets3.setText("Add and manage drivers.");

        addDriversBtn.setBackground(new java.awt.Color(28, 162, 150));
        addDriversBtn.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        addDriversBtn.setForeground(new java.awt.Color(255, 255, 255));
        addDriversBtn.setText("Add Now");
        addDriversBtn.setBorder(null);
        addDriversBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        addDriversBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDriversBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busPanel1Layout = new javax.swing.GroupLayout(busPanel1);
        busPanel1.setLayout(busPanel1Layout);
        busPanel1Layout.setHorizontalGroup(
            busPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(busPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDriversBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTickets3)
                    .addComponent(ttlTxt3))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        busPanel1Layout.setVerticalGroup(
            busPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ttlTxt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTickets3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(addDriversBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        busPanel2.setBackground(new java.awt.Color(255, 255, 255));
        busPanel2.setPreferredSize(new java.awt.Dimension(246, 147));

        ttlTxt4.setFont(new java.awt.Font("Open Sans", 1, 22)); // NOI18N
        ttlTxt4.setForeground(new java.awt.Color(255, 159, 28));
        ttlTxt4.setText("Routes");

        noTickets4.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        noTickets4.setForeground(new java.awt.Color(51, 51, 51));
        noTickets4.setText("Manage routes and departure ");

        addRoutesBtn.setBackground(new java.awt.Color(28, 162, 150));
        addRoutesBtn.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        addRoutesBtn.setForeground(new java.awt.Color(255, 255, 255));
        addRoutesBtn.setText("Add Now");
        addRoutesBtn.setBorder(null);
        addRoutesBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        addRoutesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoutesBtnActionPerformed(evt);
            }
        });

        noTickets5.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        noTickets5.setForeground(new java.awt.Color(51, 51, 51));
        noTickets5.setText("schedule.");

        javax.swing.GroupLayout busPanel2Layout = new javax.swing.GroupLayout(busPanel2);
        busPanel2.setLayout(busPanel2Layout);
        busPanel2Layout.setHorizontalGroup(
            busPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(busPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noTickets5)
                    .addComponent(addRoutesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTickets4)
                    .addComponent(ttlTxt4))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        busPanel2Layout.setVerticalGroup(
            busPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ttlTxt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTickets4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTickets5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(addRoutesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ovrvwTxt)
                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rootPanelLayout.createSequentialGroup()
                            .addComponent(ticketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(busPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(busPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(overviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(busPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 94, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(ovrvwTxt)
                .addGap(18, 18, 18)
                .addComponent(overviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(busPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addTicketsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTicketsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTicketsBtnActionPerformed

    private void viewTicketsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTicketsBtnActionPerformed

    private void addBusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBusBtnActionPerformed

    private void addDriversBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriversBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDriversBtnActionPerformed

    private void addRoutesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoutesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRoutesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // region Set the Look and Feel of the Project
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException e) {
            
        }
        // endregion

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBusBtn;
    private javax.swing.JButton addDriversBtn;
    private javax.swing.JButton addRoutesBtn;
    private javax.swing.JButton addTicketsBtn;
    private javax.swing.JPanel busPanel;
    private javax.swing.JPanel busPanel1;
    private javax.swing.JPanel busPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel noBuses;
    private javax.swing.JLabel noRoutes;
    private javax.swing.JLabel noTickets;
    private javax.swing.JLabel noTickets1;
    private javax.swing.JLabel noTickets2;
    private javax.swing.JLabel noTickets3;
    private javax.swing.JLabel noTickets4;
    private javax.swing.JLabel noTickets5;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JLabel ovrvwTxt;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel ticketPanel;
    private javax.swing.JLabel ttlBuses;
    private javax.swing.JLabel ttlRoutes;
    private javax.swing.JLabel ttlTickets;
    private javax.swing.JLabel ttlTxt1;
    private javax.swing.JLabel ttlTxt2;
    private javax.swing.JLabel ttlTxt3;
    private javax.swing.JLabel ttlTxt4;
    private javax.swing.JButton viewTicketsBtn;
    // End of variables declaration//GEN-END:variables
}
