/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import UtilityClasses.JTextFieldCharLimit;
import UtilityClasses.SetIcon;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdk.dynalink.beans.StaticClass;

import UtilityClasses.StaticVar;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author clare
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        userField.setDocument(new JTextFieldCharLimit(6));
        passField.setDocument(new JTextFieldCharLimit(6));
        
        

        setIcon();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        loginBasePanel = new javax.swing.JPanel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        forgotPassBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LAKBAY Login");
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("Lakbay Ticket Management System: Login Page"); // NOI18N
        setResizable(false);

        loginBasePanel.setBackground(new java.awt.Color(255, 255, 255));
        loginBasePanel.setPreferredSize(new java.awt.Dimension(461, 720));

        userField.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        userField.setToolTipText("HELLO");
        userField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 196, 182), 2, true), "Username:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Open Sans", 0, 16), new java.awt.Color(102, 102, 102))); // NOI18N

        passField.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        passField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 196, 182), 2, true), "Password:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Open Sans", 0, 16), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 159, 28));
        jLabel2.setText("LOGIN");

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel1.setText("Enter your account details");

        jButton1.setBackground(new java.awt.Color(46, 196, 182));
        jButton1.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        forgotPassBtn.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        forgotPassBtn.setForeground(new java.awt.Color(0, 204, 204));
        forgotPassBtn.setText("I forgot my password.");
        forgotPassBtn.setToolTipText("");
        forgotPassBtn.setBorder(null);
        forgotPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPassBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginBasePanelLayout = new javax.swing.GroupLayout(loginBasePanel);
        loginBasePanel.setLayout(loginBasePanelLayout);
        loginBasePanelLayout.setHorizontalGroup(
            loginBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBasePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(loginBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginBasePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(loginBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(forgotPassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        loginBasePanelLayout.setVerticalGroup(
            loginBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBasePanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotPassBtn)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cashier-Illustration.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 27)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 159, 28));
        jLabel3.setText("LAKBAY BUS TICKET MANAGEMENT SYSTEM");

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(loginBasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(89, 89, 89))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(loginBasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       
    public void close()
    {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    // Connect database code
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public void sqlConnect()
    {
        try {
           String url1 = "jdbc:mysql://localhost:3306/lakbay_ticket_management_system";
           String user = "root";
           String password = "Cj06032002";
           
           con = DriverManager.getConnection(url1, user, password);
           if(con != null)
           {
               //System.out.println("Connected to the database.");
           }
           
        } catch (SQLException ex) {
            System.out.println("An error occurred. Maybe user/password is invalid");
            ex.printStackTrace();
        }
    }
    
    public boolean Login(String u, String p){
        sqlConnect();
        try {
            ps = con.prepareStatement("SELECT * FROM staff");
            rs = ps.executeQuery();
            
            while(rs.next())
            {
                String uname = rs.getString("user_name");
                String pword = rs.getString("pass_word");
                String fname = rs.getString("staff_id");
                int attempts = rs.getInt("login_attempt_count");
                
                if(u.equals(uname) && p.equals(pword))
                {
                    
                    
                    if (attempts <= 3) {
                        
                        close();
                        return true;
                        
                    }
                    
                }
                            
            }
                    
        } catch (SQLException ex) 
        {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    public void updateAttempt(int newNum, String u)
    {
        
        try {
            sqlConnect();
            String query = "UPDATE staff SET "
                    + "login_attempt_count = ? "
                    + "WHERE user_name = ?";

            ps = con.prepareStatement(query);
            
            ps.setInt(1, newNum);
            ps.setString(2, u);
            
            int k = ps.executeUpdate();
            
            if(k==1)
            {
                System.out.println("Login Attempt Updated " + newNum);
            }
            else{
                System.out.println("Failed to attempt.");
            }
               
            
        } catch (Exception e) {
            System.out.println("may error update: " + e);
        }    
        
    }
    
    public int getAttempt(String u)
    {
        
        
        String query = 
                "SELECT login_attempt_count FROM staff WHERE user_name = ?";
        
        try {
            sqlConnect();
            ps = con.prepareStatement(query);
            ps.setString(1, u);
            rs = ps.executeQuery();
            
            while(rs.next())
            {    
                int attemptCount = rs.getInt("login_attempt_count");
                return attemptCount;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return 0;
    }

    // Retrieve Dataa
    public String getString(String u)
    {
        String fName = null;
        
        String query = 
                "SELECT staff_id FROM staff WHERE user_name = ?";
        
        try {
            ps = con.prepareStatement(query);
            ps.setString(1, u);
            rs = ps.executeQuery();
            
            while(rs.next())
            {    
                fName = rs.getString("staff_id");
                return fName;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return fName;
    }
    
    public void clearFields()
    {
        userField.setText("");
        passField.setText("");
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       

        // TODO add your handling code here:
        String username = userField.getText();
        String password = String.valueOf(passField.getText());
        
        
        
        if (Login(username, password))
        {
            StaticVar.userId = getString(username);
            StaticVar.userName = username;
            
            if(StaticVar.userId.contains("AD"))
            {
                StaticVar.privilege = "Admin";
            }
            else if (StaticVar.userId.contains("MG")) {
                StaticVar.privilege = "Manager";
            }
            else if (StaticVar.userId.contains("CS")) {
                StaticVar.privilege = "Cashier";
            }
            
            
            HomePage hp = new HomePage();
            hp.setVisible(true);
            
            updateAttempt(0, username);
            
            clearFields();
        }
        else if(!Login(username, password))
        {
            int newLoginAttemptCount = getAttempt(username) + 1;
            
            if (newLoginAttemptCount < 4) {
                
                JOptionPane.showMessageDialog(rootPane, "Please double check your details or\n"
                    + "contact the administrator.",
                    "Login error.",
                    JOptionPane.ERROR_MESSAGE);
                updateAttempt(newLoginAttemptCount, username);
                
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Your account is blocked. Contact your admin to reset your account",
                    "Login error.",
                    JOptionPane.ERROR_MESSAGE);
            }
            

            clearFields();

        }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void forgotPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPassBtnActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        PasswordReset pr = new PasswordReset();
        pr.setVisible(true);
        
    }//GEN-LAST:event_forgotPassBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        // region Set the Look and Feel of the Project
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException e) {
            
        }
        // endregion
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginPage().setVisible(true);
                
                
                
                
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forgotPassBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel loginBasePanel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables

    
    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\clare\\Documents\\Programming\\JavaNetbeans\\LakbayTicketManagementSystem\\LakbayTicketManagementSystem\\LakbayTicketManagementSystem\\LakbayTicketManagementSystem\\src\\Images\\Icons\\bus_window_icon_64x64.png"));
    }
    
}
